trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_ACCESS_KEY_ID: 'AKIAYJTBCUMT3RJGQEHO'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_REGION: 'us-east-1' # Cambia esto a tu región deseada
  TF_CLI_ARGS: '-input=false -no-color'

jobs:
- job: DeployInfrastructure
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      echo "##vso[task.setvariable variable=TF_VAR_aws_access_key]$(AWS_ACCESS_KEY_ID)"
      echo "##vso[task.setvariable variable=TF_VAR_aws_secret_key]$(AWS_SECRET_ACCESS_KEY)"
    displayName: 'Set Terraform Variables'

  - script: 'curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg'
    displayName: 'Add HashiCorp GPG Key'

  - script: |
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update
      sudo apt-get install terraform
    displayName: 'Install Terraform'

  - script: 'terraform init'
    displayName: 'Terraform Init'

  - script: 'terraform apply -auto-approve'
    displayName: 'Terraform Apply'

  - script: 'terraform destroy -auto-approve'
    displayName: 'Terraform Destroy'

  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_REGION: $(AWS_REGION)